AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  This template deploys a RDS SQL Server into an existing VPC for the Ed-Fi Quick
  Deploy solution. **WARNING** This template creates an RDS. You will be billed for
  the AWS resources used if you create a stack from this template.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Network configuration
        Parameters:
          - VPCID
          - PrivateSubnet1ID
          - PrivateSubnet2ID
          - RDSSecurityGroupID
      - Label:
          default: SQL Server configuration
        Parameters:
          - Environment
          - EnvLabel
          - PubliclyAccessible
          - Encrypt
          - DBInstanceClass
          - BackupRetentionPeriod
          - DBAutoMinorVersionUpgrade
          - SQLEngineEdition
          - SQLEngineVersion
          - RDSOptionGroup
          - SQLMasterUserName
          - SQLMasterUserPassword
          - VolumeSize
          - VolumeType
    ParameterLabels:
      Environment:
        default: MultiAZ or SingleAZ
      EnvLabel:
        default: Label your environment
      Encrypt:
        default: Encrypt the database at-rest
      BackupRetentionPeriod:
        default: Number of days to keep a backup
      DBInstanceClass:
        default: The instance size of the RDS
      PubliclyAccessible:
        default: Is the database avaiable publicly?
      DBAutoMinorVersionUpgrade:
        default: Database auto minor version upgrade
      SQLEngineEdition:
        default: MSSQL database engine edition
      SQLEngineVersion:
        default: MSSQL database engine version
      SQLMasterUserName:
        default: SQL Server master user name
      SQLMasterUserPassword:
        default: SQL Server password
      RDSOptionGroup:
        default: RDS Option Group
      PrivateSubnet1ID:
        default: Private subnet 1 ID
      PrivateSubnet2ID:
        default: Private subnet 2 ID
      PrivateSubnet3ID:
        default: Private subnet 3 ID
      VolumeSize:
        default: Data volume size
      VolumeType:
        default: Data volume type
      VPCID:
        default: VPC ID
      RDSSecurityGroupID:
        default: RDS Security Group ID
Parameters:
  Environment:
    AllowedValues:
      - prod
      - nonprod
    Default: nonprod
    Description: Select the type of environment this RDS will reside.
    Type: String
  EnvLabel:
    Default: test
    Description: Provide a label for your environment to identify resources easier.
    Type: String
  DBAutoMinorVersionUpgrade:
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'false'
    Description: Select true to set up auto minor version upgrade.
    Type: String
  PrivateSubnet1ID:
    Description: ID of the private subnet 1 in Availability Zone 1 (e.g., subnet-a0246dcd)
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet2ID:
    Description: ID of the private subnet 2 in Availability Zone 2 (e.g., subnet-a0246dcd)
    Type: AWS::EC2::Subnet::Id
  PubliclyAccessible:
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'false'
    Description: Select whether DB instance is internet-facing.
    Type: String
  DBInstanceClass:
    AllowedValues:
      - db.m5.large
      - db.m5.xlarge
      - db.m5.2xlarge
      - db.m5.4xlarge
      - db.m5.12xlarge
      - db.m5.24xlarge
      - db.m4.large
      - db.m4.xlarge
      - db.m4.2xlarge
      - db.m4.4xlarge
      - db.m4.10xlarge
      - db.m4.16xlarge
      - db.r4.large
      - db.r4.xlarge
      - db.r4.2xlarge
      - db.r4.4xlarge
      - db.r4.8xlarge
      - db.r4.16xlarge
    ConstraintDescription: Must select a valid database instance type.
    Default: db.m5.large
    Description: The name of the compute and memory capacity class of the database
      instance.
    Type: String
  SQLEngineEdition:
    AllowedValues:
      - sqlserver-ee
      - sqlserver-se
    ConstraintDescription: Must select a MSSQL Database Engine Edition.
    Default: sqlserver-se
    Description: MSSQL Database Engine Edition.
    Type: String
  SQLEngineVersion:
    AllowedValues:
      - 14.00.3049.1.v1
      - 14.00.3035.2.v1
      - 14.00.3015.40.v1
      - 14.00.1000.169.v1
      - 13.00.5292.0.v1
    ConstraintDescription: Must select a MSSQL Database Engine Version.
    Default: 13.00.5292.0.v1
    Description: MSSQL Database Engine Version.
    Type: String
  BackupRetentionPeriod:
    Default: 7
    Description: The number of days for which automated backups are retained. Setting
      this parameter to a positive number enables backups. Setting this parameter
      to 0 disables automated backups.
    Type: Number
  SQLMasterUserName:
    AllowedPattern: '[a-zA-Z0-9]*'
    Default: sqlsa
    Description: SQL Server master user name.
    MaxLength: '25'
    MinLength: '5'
    Type: String
  SQLMasterUserPassword:
    AllowedPattern: (?=^.{6,255}$)((?=.*\d)(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[^A-Za-z0-9])(?=.*[a-z])|(?=.*[^A-Za-z0-9])(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[A-Z])(?=.*[^A-Za-z0-9]))^.*
    Description: Password for the SQL master user. Must be at least 8 characters containing
      letters, numbers and symbols
    MaxLength: '32'
    MinLength: '8'
    NoEcho: 'true'
    Type: String
  RDSOptionGroup:
    Type: String
    Default: default:sqlserver-se-13-00
  VolumeSize:
    Default: '100'
    Description: Volume size for the SQL Data, Logs and TempDb volumes, in GiB
    MaxValue: '16000'
    MinValue: '100'
    Type: Number
  VolumeType:
    AllowedValues:
      - gp2
      - magnetic
    Default: gp2
    Description: Volume type of database storage
    Type: String
  VPCID:
    Description: ID of the VPC (e.g., vpc-0343606e)
    Type: AWS::EC2::VPC::Id
  RDSSecurityGroupID:
    Description: Security Group ID to use with this RDS (e.g., sg-7f16e910).
    Type: AWS::EC2::SecurityGroup::Id
  Encrypt:
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'
    Description: Encrypt the RDS At-Rest
    Type: String
Conditions:
  GovCloudCondition: !Equals
    - !Ref 'AWS::Region'
    - us-gov-west-1
Rules:
  SubnetsInVPC:
    Assertions:
      - Assert: !EachMemberIn
          - !ValueOfAll
            - AWS::EC2::Subnet::Id
            - VpcId
          - !RefAll 'AWS::EC2::VPC::Id'
        AssertDescription: All subnets must in the VPC
Resources:
  RDSSQLDBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: !Sub 'Ed-Fi RDS Subnet Group for ${AWS::StackName}
        RDS SQL'
      DBSubnetGroupName: !Sub '${AWS::StackName}-DBSubnetGroup'
      SubnetIds:
        - !Ref 'PrivateSubnet1ID'
        - !Ref 'PrivateSubnet2ID'
  RDSSQL:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    Properties:
      AutoMinorVersionUpgrade: !Ref 'DBAutoMinorVersionUpgrade'
      AllocatedStorage: !Ref 'VolumeSize'
      BackupRetentionPeriod: !Ref 'BackupRetentionPeriod'
      DBInstanceClass: !Ref 'DBInstanceClass'
      StorageType: !Ref 'VolumeType'
      DBSubnetGroupName: !Ref 'RDSSQLDBSubnetGroup'
      OptionGroupName: !Ref 'RDSOptionGroup'
      Engine: !Ref 'SQLEngineEdition'
      EngineVersion: !Ref 'SQLEngineVersion'
      LicenseModel: license-included
      MasterUserPassword: !Ref 'SQLMasterUserPassword'
      MasterUsername: !Ref 'SQLMasterUserName'
      MultiAZ: 'false'
      VPCSecurityGroups:
        - !Ref 'RDSSecurityGroupID'
      PubliclyAccessible: !Ref 'PubliclyAccessible'
      StorageEncrypted: !Ref 'Encrypt'
      Tags:
        - Key: Name
          Value: !Join
            - '-'
            - - EdFi ODS API Database Server
              - !Ref 'EnvLabel'
        - Key: Environment
          Value: !Ref 'EnvLabel'
Outputs:
  RDSSQLEndpoint:
    Description: Database endpoint
    Value: !Sub '${RDSSQL.Endpoint.Address}'
    Export:
      Name: !Sub '${AWS::StackName}-RDSSQLEndpoint'
  RDSName:
    Description: 'RDS AWS Name '
    Value: !Ref 'RDSSQL'
    Export:
      Name: !Sub '${AWS::StackName}-RDSName'
