AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  This template provides the custom resources for the EdFi ODS Deployment.  ** WARNING
  **  You will be billed for the AWS resources that are created from this template.  There
  is no cost to use this template, but are responsible for the costs incurred by the
  resources created in this template.
Parameters:
  EnvLabel:
    Default: ''
    Description: Provide a label for your environment to identify resources easier.
    Type: String
  KmsKeyId:
    Default: ''
    Description: The KMS Key ID used to encrypt values.
    Type: String
  RDGWPassword:
    Description: Password for the ODS API RDGW local administrative account.
    Type: String
    NoEcho: 'true'
  AdminAppPassword:
    Description: Password for the ODS API Admin Application local administrative account.
    Type: String
    NoEcho: 'true'
  OdsApiPassword:
    Description: Password for the ODS API Application local administrative account.
    Type: String
    NoEcho: 'true'
  RDSPassword:
    Description: Password for the ODS API RDS database administrative account.
    Type: String
    NoEcho: 'true'
  S3BucketSecureStore:
    Type: String
    Default: ''
    Description: This provides a location where the SSH Private Key pair file can
      be saved in S3.
Resources:
  ManagedKeyPairResource:
    Type: Custom::ManagedKeyPair
    Properties:
      ServiceToken: !Join
        - ''
        - - 'arn:aws:lambda:'
          - !Ref 'AWS::Region'
          - ':'
          - !Ref 'AWS::AccountId'
          - ':function:edfi-ssh-key-generator-'
          - !Ref 'EnvLabel'
      region: !Ref 'AWS::Region'
      bucket_name: !Ref 'S3BucketSecureStore'
      key_pair_name: !Join
        - ''
        - - edfi-ods-ssh-key-
          - !Ref 'EnvLabel'
  RDGWStoredAdminPassword:
    Type: Custom::ManagedPassword
    Properties:
      ServiceToken: !Join
        - ''
        - - 'arn:aws:lambda:'
          - !Ref 'AWS::Region'
          - ':'
          - !Ref 'AWS::AccountId'
          - ':function:edfi-ssm-param-store-'
          - !Ref 'EnvLabel'
      region: !Ref 'AWS::Region'
      keyid: !Ref 'KmsKeyId'
      name: !Join
        - ''
        - - edfi-ods-rdgw-server-local-admin-pwd-
          - !Ref 'EnvLabel'
      value: !Ref 'RDGWPassword'
  AdminAppStoredAdminPassword:
    Type: Custom::ManagedKeyPair
    Properties:
      ServiceToken: !Join
        - ''
        - - 'arn:aws:lambda:'
          - !Ref 'AWS::Region'
          - ':'
          - !Ref 'AWS::AccountId'
          - ':function:edfi-ssm-param-store-'
          - !Ref 'EnvLabel'
      region: !Ref 'AWS::Region'
      keyid: !Ref 'KmsKeyId'
      name: !Join
        - ''
        - - edfi-ods-adminapp-server-local-admin-pwd-
          - !Ref 'EnvLabel'
      value: !Ref 'AdminAppPassword'
  OdsApiStoredAdminPassword:
    Type: Custom::ManagedKeyPair
    Properties:
      ServiceToken: !Join
        - ''
        - - 'arn:aws:lambda:'
          - !Ref 'AWS::Region'
          - ':'
          - !Ref 'AWS::AccountId'
          - ':function:edfi-ssm-param-store-'
          - !Ref 'EnvLabel'
      region: !Ref 'AWS::Region'
      keyid: !Ref 'KmsKeyId'
      name: !Join
        - ''
        - - edfi-ods-api-server-local-admin-pwd-
          - !Ref 'EnvLabel'
      value: !Ref 'OdsApiPassword'
  ManagedRDSPasswordResource:
    Type: Custom::ManagedPassword
    Properties:
      ServiceToken: !Join
        - ''
        - - 'arn:aws:lambda:'
          - !Ref 'AWS::Region'
          - ':'
          - !Ref 'AWS::AccountId'
          - ':function:edfi-ssm-param-store-'
          - !Ref 'EnvLabel'
      region: !Ref 'AWS::Region'
      keyid: !Ref 'KmsKeyId'
      name: !Join
        - ''
        - - edfi-ods-rds-admin-pwd-
          - !Ref 'EnvLabel'
      value: !Ref 'RDSPassword'
Outputs:
  KeyPairName:
    Value: !GetAtt 'ManagedKeyPairResource.KeyPairName'
    Description: The SSH key pair name in the AWS Account that was used with the EC2 instances.
    Export:
      Name: !Sub '${AWS::StackName}-SSHKeyFileName'
