AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  This template provides the custom resources specific for a Prod environment in the
  EdFi ODS Deployment.  ** WARNING **  You will be billed for the AWS resources that
  are created from this template.  There is no cost to use this template, but are
  responsible for the costs incurred by the resources created in this template.
Parameters:
  RDStoMultiAZFunctionName:
    Type: String
    Default: edfi-rds-to-multiaz
    Description: The prefix name of the lambda function that converts an RDS to Multi-AZ
  RDSName:
    Type: String
    Description: The RDS name of the system to convert to Multi-AZ
  EnvLabel:
    Default: ''
    Description: Provide a label for your environment to identify resources easier.
    Type: String
Resources:
  RDSMultiAZResource:
    Type: Custom::RDSMultiAZ
    Properties:
      ServiceToken: !Join
        - ''
        - - 'arn:aws:lambda:'
          - !Ref 'AWS::Region'
          - ':'
          - !Ref 'AWS::AccountId'
          - ':function:'
          - !Ref 'RDStoMultiAZFunctionName'
          - '-'
          - !Ref 'EnvLabel'
      region: !Ref 'AWS::Region'
      rds: !Ref 'RDSName'
Outputs: {}
