AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  This template provides the custom resources specific for a NonProd environment in
  the EdFi ODS Deployment.  ** WARNING **  You will be billed for the AWS resources
  that are created from this template.  There is no cost to use this template, but
  are responsible for the costs incurred by the resources created in this template.
Parameters:
  Ec2ToElbFunctionName:
    Type: String
    Default: edfi-ec2-attach-elb
    Description: 'The prefix name of the lambda function that attachs an EC2 to and
      ELB '
  EnvLabel:
    Default: ''
    Description: Provide a label for your environment to identify resources easier.
    Type: String
  ELBName1:
    Default: ''
    Description: Provide the name of a Classic ELB to attach an EC2 instance
    Type: String
  InstanceID1:
    Default: ''
    Description: Provide the Instance ID to attach to the ELB
    Type: String
Resources:
  AttachEc2ToElbNonProd:
    Type: Custom::ManagedAttachEc2
    Properties:
      ServiceToken: !Join
        - ''
        - - 'arn:aws:lambda:'
          - !Ref 'AWS::Region'
          - ':'
          - !Ref 'AWS::AccountId'
          - ':function:'
          - !Ref 'Ec2ToElbFunctionName'
          - '-'
          - !Ref 'EnvLabel'
      region: !Ref 'AWS::Region'
      ec2: !Ref 'InstanceID1'
      elb: !Ref 'ELBName1'
Outputs: {}
