AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  This template provides the custom resources that will populate the EdFi ODS database.  **
  WARNING **  You will be billed for the AWS resources that are created from this
  template.  There is no cost to use this template, but are responsible for the costs
  incurred by the resources created in this template.
Parameters:
  RDSUsername:
    Type: String
    Default: sqlsa
  RDSPassword:
    Type: String
    NoEcho: 'true'
  RDSHost:
    Type: String
  DBEngine:
    Description: The database engine software
    Type: String
    AllowedValues:
      - PostgreSQL
      - SQLServer
    ConstraintDescription: Choose a support database engine
    Default: SQLServer
  RestoreAdminDB:
    Type: String
    Default: 'yes'
    AllowedValues:
      - 'yes'
      - 'no'
  RestoreSecurityDB:
    Type: String
    Default: 'yes'
    AllowedValues:
      - 'yes'
      - 'no'
  RestoreMinimalDB:
    Type: String
    Default: 'yes'
    AllowedValues:
      - 'yes'
      - 'no'
  RestorePopulatedDB:
    Type: String
    Default: 'no'
    AllowedValues:
      - 'yes'
      - 'no'
  RestoreEmptyDB:
    Type: String
    Default: 'no'
    AllowedValues:
      - 'yes'
      - 'no'
  S3SourceBucket:
    Type: String
    Default: edfi-aws-quick-deploy
  S3SourceKeyName:
    Type: String
    Default: sqlserver
  AdminDBBakS3Name:
    Type: String
    Default: EdFi_Admin
  SecurityDBBakS3Name:
    Type: String
    Default: EdFi_Security
  MinimalDBBakS3Name:
    Type: String
    Default: EdFi_Ods_Minimal_Template
  PopulatedDBBakS3Name:
    Type: String
    Default: EdFi_Ods_Populated_Template
  EmptyDBBakS3Name:
    Type: String
    Default: EdFi_Ods
  LambdaFunctionName:
    Type: String
    Default: edfi-ods-lambda-db-restore
Conditions:
  UseSQLServer: !Equals
    - !Ref DBEngine
    - 'SQLServer'
  UsePostgresServer: !Equals
    - !Ref DBEngine
    - 'PostgreSQL'
  RestoreTheAdminDB: !Equals
    - !Ref 'RestoreAdminDB'
    - 'yes'
  RestoreTheSecurityDB: !Equals
    - !Ref 'RestoreSecurityDB'
    - 'yes'
  RestoreTheMinimalDB: !Equals
    - !Ref 'RestoreMinimalDB'
    - 'yes'
  RestoreThePopulatedDB: !Equals
    - !Ref 'RestorePopulatedDB'
    - 'yes'
  RestoreTheEmptyDB: !Equals
    - !Ref 'RestoreEmptyDB'
    - 'yes'
  RestoreAdminWithSQLServer: !And
    - !Condition 'RestoreTheAdminDB'
    - !Condition 'UseSQLServer'
  RestoreSecurityWithSQLServer: !And
    - !Condition 'RestoreTheSecurityDB'
    - !Condition 'UseSQLServer'
  RestorePopulatedWithSQLServer: !And
    - !Condition 'RestoreThePopulatedDB'
    - !Condition 'UseSQLServer'
  RestoreMinimalWithSQLServer: !And
    - !Condition 'RestoreTheMinimalDB'
    - !Condition 'UseSQLServer'
  RestoreEmptyWithSQLServer: !And
    - !Condition 'RestoreTheEmptyDB'
    - !Condition 'UseSQLServer'
  RestoreAdminWithPostgres: !And
    - !Condition 'RestoreTheAdminDB'
    - !Condition 'UsePostgresServer'
  RestoreSecurityWithPostgres: !And
    - !Condition 'RestoreTheSecurityDB'
    - !Condition 'UsePostgresServer'
  RestorePopulatedWithPostgres: !And
    - !Condition 'RestoreThePopulatedDB'
    - !Condition 'UsePostgresServer'
  RestoreMinimalWithPostgres: !And
    - !Condition 'RestoreTheMinimalDB'
    - !Condition 'UsePostgresServer'
  RestoreEmptyWithPostgres: !And
    - !Condition 'RestoreTheEmptyDB'
    - !Condition 'UsePostgresServer' 
Resources:
  MSSQLDBRestoreEmptyResource:
    Condition: RestoreEmptyWithSQLServer
    Type: Custom::MSSQLDBRestore
    Properties:
      ServiceToken: !Join
        - ''
        - - 'arn:aws:lambda:'
          - !Ref 'AWS::Region'
          - ':'
          - !Ref 'AWS::AccountId'
          - ':function:'
          - !Ref 'LambdaFunctionName'
      source: !Join
        - ''
        - - 'arn:aws:s3:::'
          - !Ref 'S3SourceBucket'
          - /
          - !Ref 'S3SourceKeyName'
          - /
          - !Ref 'EmptyDBBakS3Name'
          - '.bak'
      server: !Ref 'RDSHost'
      database: EdFi_Ods
      username: !Ref 'RDSUsername'
      pwdname: !Ref 'RDSPassword'
  MSSQLDBRestoreAdminResource:
    Condition: RestoreAdminWithSQLServer
    DependsOn: MSSQLDBRestoreSecurityResource
    Type: Custom::MSSQLDBRestore
    Properties:
      ServiceToken: !Join
        - ''
        - - 'arn:aws:lambda:'
          - !Ref 'AWS::Region'
          - ':'
          - !Ref 'AWS::AccountId'
          - ':function:'
          - !Ref 'LambdaFunctionName'
      source: !Join
        - ''
        - - 'arn:aws:s3:::'
          - !Ref 'S3SourceBucket'
          - /
          - !Ref 'S3SourceKeyName'
          - /
          - !Ref 'AdminDBBakS3Name'
          - '.bak'
      server: !Ref 'RDSHost'
      database: EdFi_Admin
      username: !Ref 'RDSUsername'
      pwdname: !Ref 'RDSPassword'
  MSSQLDBRestoreMinimalResource:
    Condition: RestoreMinimalWithSQLServer
    DependsOn: MSSQLDBRestoreSecurityResource
    Type: Custom::MSSQLDBRestore
    Properties:
      ServiceToken: !Join
        - ''
        - - 'arn:aws:lambda:'
          - !Ref 'AWS::Region'
          - ':'
          - !Ref 'AWS::AccountId'
          - ':function:'
          - !Ref 'LambdaFunctionName'
      source: !Join
        - ''
        - - 'arn:aws:s3:::'
          - !Ref 'S3SourceBucket'
          - /
          - !Ref 'S3SourceKeyName'
          - /
          - !Ref 'MinimalDBBakS3Name'
          - '.bak'
      server: !Ref 'RDSHost'
      database: EdFi_Ods
      username: !Ref 'RDSUsername'
      pwdname: !Ref 'RDSPassword'
  MSSQLDBRestorePopulatedResource:
    Condition: RestorePopulatedWithSQLServer
    DependsOn: MSSQLDBRestoreSecurityResource
    Type: Custom::MSSQLDBRestore
    Properties:
      ServiceToken: !Join
        - ''
        - - 'arn:aws:lambda:'
          - !Ref 'AWS::Region'
          - ':'
          - !Ref 'AWS::AccountId'
          - ':function:'
          - !Ref 'LambdaFunctionName'
      source: !Join
        - ''
        - - 'arn:aws:s3:::'
          - !Ref 'S3SourceBucket'
          - /
          - !Ref 'S3SourceKeyName'
          - /
          - !Ref 'PopulatedDBBakS3Name'
          - '.bak'
      server: !Ref 'RDSHost'
      database: EdFi_Ods
      username: !Ref 'RDSUsername'
      pwdname: !Ref 'RDSPassword'
  MSSQLDBRestoreSecurityResource:
    Condition: RestoreSecurityWithSQLServer
    Type: Custom::MSSQLDBRestore
    Properties:
      ServiceToken: !Join
        - ''
        - - 'arn:aws:lambda:'
          - !Ref 'AWS::Region'
          - ':'
          - !Ref 'AWS::AccountId'
          - ':function:'
          - !Ref 'LambdaFunctionName'
      source: !Join
        - ''
        - - 'arn:aws:s3:::'
          - !Ref 'S3SourceBucket'
          - /
          - !Ref 'S3SourceKeyName'
          - /
          - !Ref 'SecurityDBBakS3Name'
          - '.bak'
      server: !Ref 'RDSHost'
      database: EdFi_Security
      username: !Ref 'RDSUsername'
      pwdname: !Ref 'RDSPassword'
  PostgresDBRestoreEmptyResource:
    Condition: RestoreEmptyWithPostgres
    Type: Custom::PostgresDBRestore
    Properties:
      ServiceToken: !Join
        - ''
        - - 'arn:aws:lambda:'
          - !Ref 'AWS::Region'
          - ':'
          - !Ref 'AWS::AccountId'
          - ':function:'
          - !Ref 'LambdaFunctionName'
      bucket: !Ref 'S3SourceBucket'
      bucket_key: !Join
        - ''
        - - !Ref 'S3SourceKeyName'
          - /
          - !Ref 'EmptyDBBakS3Name'
          - '.sql'
      server: !Ref 'RDSHost'
      database: EdFi_Ods
      username: !Ref 'RDSUsername'
      password: !Ref 'RDSPassword'
      region: !Ref 'AWS::Region'
  PostgresDBRestoreAdminResource:
    Condition: RestoreAdminWithPostgres
    DependsOn: PostgresDBRestoreSecurityResource
    Type: Custom::PostgresDBRestore
    Properties:
      ServiceToken: !Join
        - ''
        - - 'arn:aws:lambda:'
          - !Ref 'AWS::Region'
          - ':'
          - !Ref 'AWS::AccountId'
          - ':function:'
          - !Ref 'LambdaFunctionName'
      bucket: !Ref 'S3SourceBucket'
      bucket_key: !Join
        - ''
        - - !Ref 'S3SourceKeyName'
          - /
          - !Ref 'AdminDBBakS3Name'
          - '.sql'
      server: !Ref 'RDSHost'
      database: EdFi_Admin
      username: !Ref 'RDSUsername'
      password: !Ref 'RDSPassword'
      region: !Ref 'AWS::Region'
  PostgresDBRestoreMinimalResource:
    Condition: RestoreMinimalWithPostgres
    DependsOn: PostgresDBRestoreSecurityResource
    Type: Custom::PostgresDBRestore
    Properties:
      ServiceToken: !Join
        - ''
        - - 'arn:aws:lambda:'
          - !Ref 'AWS::Region'
          - ':'
          - !Ref 'AWS::AccountId'
          - ':function:'
          - !Ref 'LambdaFunctionName'
      bucket: !Ref 'S3SourceBucket'
      bucket_key: !Join
        - ''
        - - !Ref 'S3SourceKeyName'
          - /
          - !Ref 'MinimalDBBakS3Name'
          - '.sql'
      server: !Ref 'RDSHost'
      database: EdFi_Ods
      username: !Ref 'RDSUsername'
      password: !Ref 'RDSPassword'
      region: !Ref 'AWS::Region'
  PostgresDBRestorePopulatedResource:
    Condition: RestorePopulatedWithPostgres
    DependsOn: PostgresDBRestoreSecurityResource
    Type: Custom::PostgresDBRestore
    Properties:
      ServiceToken: !Join
        - ''
        - - 'arn:aws:lambda:'
          - !Ref 'AWS::Region'
          - ':'
          - !Ref 'AWS::AccountId'
          - ':function:'
          - !Ref 'LambdaFunctionName'
      bucket: !Ref 'S3SourceBucket'
      bucket_key: !Join
        - ''
        - - !Ref 'S3SourceKeyName'
          - /
          - !Ref 'PopulatedDBBakS3Name'
          - '.sql'
      server: !Ref 'RDSHost'
      database: EdFi_Ods
      username: !Ref 'RDSUsername'
      password: !Ref 'RDSPassword'
      region: !Ref 'AWS::Region'
  PostgresDBRestoreSecurityResource:
    Condition: RestoreSecurityWithPostgres
    Type: Custom::PostgresDBRestore
    Properties:
      ServiceToken: !Join
        - ''
        - - 'arn:aws:lambda:'
          - !Ref 'AWS::Region'
          - ':'
          - !Ref 'AWS::AccountId'
          - ':function:'
          - !Ref 'LambdaFunctionName'
      bucket: !Ref 'S3SourceBucket'
      bucket_key: !Join
        - ''
        - - !Ref 'S3SourceKeyName'
          - /
          - !Ref 'SecurityDBBakS3Name'
          - '.sql'
      server: !Ref 'RDSHost'
      database: EdFi_Security
      username: !Ref 'RDSUsername'
      password: !Ref 'RDSPassword'
      region: !Ref 'AWS::Region'
